"""Shared constants, translations and utility helpers for DrivePulse."""
from __future__ import annotations

import os
from pathlib import Path

import gi

gi.require_version("Gtk", "4.0")
from gi.repository import Gtk, Pango  # noqa: E402

# ---------------------------------------------------------------------------
# Paths and OBD configuration
# ---------------------------------------------------------------------------

APP_ID = "de.cais.DrivePulse"
LOG_DIR = Path(os.environ.get("OBD_LOG_DIR", Path.home() / ".local" / "state" / "drivepulse"))
LOG_FILE = LOG_DIR / "obd-log.jsonl"
CONNECTION_LOG_FILE = LOG_DIR / "connection-log.jsonl"
PROFILES_DIR = LOG_DIR / "profiles"
THEMES_DIR = LOG_DIR / "themes"
POLL_INTERVAL_SECONDS = float(os.environ.get("OBD_POLL_INTERVAL", "0.5"))
OBD_PORT = os.environ.get("OBD_PORT")
OBD_BAUDRATE = int(os.environ["OBD_BAUDRATE"]) if os.environ.get("OBD_BAUDRATE") else None
OBD_TIMEOUT_SECONDS = float(os.environ.get("OBD_TIMEOUT", "2.0"))
OBD_FAST = os.environ.get("OBD_FAST", "1").lower() in {"1", "true", "yes", "on"}
# Direct Bluetooth RFCOMM: comma-separated addresses, optional channel suffix
# e.g. "00:1D:A5:68:98:8A" or "00:1D:A5:68:98:8A:1" or "AA:BB:CC:DD:EE:FF:1,11:22:33:44:55:66"
OBD_BT_ADDR = os.environ.get("OBD_BT_ADDR")
# socat/TCP bridge URL passed directly to pyserial, e.g. "socket://localhost:35000"
OBD_SOCKET_URL = os.environ.get("OBD_SOCKET_URL")
SETTINGS_FILE = LOG_DIR / "settings.json"
DB_FILE = LOG_DIR / "drives.sqlite3"

# ---------------------------------------------------------------------------
# Translations
# ---------------------------------------------------------------------------

SOURCE_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("en", "de")
TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "acceleration.title": "Acceleration",
        "acceleration.ready": "Ready. Press Start and accelerate.",
        "acceleration.armed": "Armed. Timing starts when acceleration is detected.",
        "acceleration.running": "Measurement running...",
        "acceleration.done": "Measurement complete.",
        "acceleration.g": "G: {value}",
        "acceleration.g.empty": "G: --",
        "acceleration.vmax": "Vmax {value}",
        "acceleration.vmax.empty": "Vmax --",
        "acceleration.vmax.in": "in",
        "acceleration.gmax": "G·max {value}",
        "acceleration.gmax.empty": "G·max --",
        "acceleration.start": "Start",
        "acceleration.abort": "Abort",
        "acceleration.reset": "Reset",
        "acceleration.best": "Ø",
        "acceleration.obd": "OBD",
        "acceleration.gps": "GPS",
        "acceleration.gforce_trigger": "Start when G-forces act",
        "acceleration.replay": "Replay",
        "acceleration.replay.running": "Replaying...",
        "cars.metric.speed_kmh":   "Speed",
        "cars.metric.rpm":         "RPM",
        "cars.metric.coolant_c":   "Coolant Temp.",
        "cars.metric.intake_c":    "Intake Air Temp.",
        "cars.metric.throttle_pct": "Throttle",
        "cars.metric.engine_load": "Engine Load",
        "cars.metric.maf_gps":     "Air Mass",
        "cars.metric.voltage_v":   "Voltage",
        "cars.metric.accel_g":     "Acceleration",
        "cars.metric.fuel_pct":    "Fuel",
        "settings.title": "Settings",
        "settings.display": "Display",
        "settings.units": "Units",
        "settings.speed": "Speed",
        "settings.metric": "Metric (km/h)",
        "settings.imperial": "Imperial (mph)",
        "settings.language": "Language",
        "settings.language.en": "English",
        "settings.language.de": "Deutsch",
        "settings.auto_rotate": "Auto-Rotate",
        "settings.auto_rotate.subtitle": "Rotate display to match device orientation",
        "settings.mock_mode": "Mock Mode",
        "settings.mock_mode.subtitle": "Simulate OBD and GPS data without hardware",
        "settings.obd": "OBD",
        "settings.obd_dongle": "Dongle",
        "settings.obd_dongle.auto": "Auto-detect",
        "settings.obd_dongle.none_found": "No dongle found",
        "settings.gauge_theme": "Gauge Style",
        "settings.gauge_theme.cockpit": "Cockpit",
        "settings.gauge_theme.neon": "Neon",
        "settings.gauge_theme.minimal": "Minimal",
        "settings.gauge_theme.digital": "Digital",
        "settings.gauge_theme.racing": "Racing",
        "settings.gauge_theme.analog": "Analog",
        "gauge.rpm": "RPM",
        "gauge.speed": "Speed",
        "gauge.coolant": "Coolant",
        "gauge.source.obd": "OBD",
        "gauge.source.gps": "GPS",
        "dashboard.rpm": "RPM",
        "dashboard.rpm.unit": "rpm",
        "dashboard.coolant": "Coolant",
        "dashboard.heading": "Heading",
        "dashboard.fuel": "Fuel",
        "dashboard.cardinal.N":  "N",
        "dashboard.cardinal.NE": "NE",
        "dashboard.cardinal.E":  "E",
        "dashboard.cardinal.SE": "SE",
        "dashboard.cardinal.S":  "S",
        "dashboard.cardinal.SW": "SW",
        "dashboard.cardinal.W":  "W",
        "dashboard.cardinal.NW": "NW",
        "status.connecting": "Connecting...",
        "status.obd": "OBD",
        "status.gps": "GPS",

        "status.updated": "{status} | last update: {time}",
        "nav.gauges": "Gauges",
        "nav.acceleration": "Acceleration",
        "nav.cars": "Cars",
        "cars.list.intro": "Select a vehicle to view its values.",
        "cars.empty": "No vehicles saved yet. Connect to an OBD dongle — a profile will be created automatically on first scan.",
        "cars.live.title": "Live connection",
        "cars.live.subtitle": "No OBD connection",
        "cars.live.connected": "OBD connected",
        "cars.unknown": "Vehicle",
        "cars.back": "Back",
        "cars.categories": "Categories",
        "cars.source.label": "Source: {source}",
        "cars.dtc.none": "No faults",
        "cars.trips.empty": "No trips recorded for this vehicle yet.",
        "cars.category.vehicle":      "Vehicle",
        "cars.category.engine":       "Engine",
        "cars.category.drive":        "Speed & Distance",
        "cars.category.temperatures": "Temperatures",
        "cars.category.throttle":     "Throttle & Pedal",
        "cars.category.mixture":      "Mixture & Lambda",
        "cars.category.fuel":         "Fuel & Air",
        "cars.category.diagnostics":  "Diagnostics",
        "cars.category.trips":        "Trips",
        "cars.pid.VIN":               "Vehicle Identification Number (VIN)",
        "cars.pid.CAL":               "ECU Software (Cal-ID)",
        "cars.pid.CVN":               "Software Checksum (CVN)",
        "cars.pid.PROTO":             "Diagnostic Protocol",
        "cars.pid.011C":              "OBD Standard",
        "cars.pid.SCAN_DATE":         "Last Scan",
        "cars.pid.010C":              "RPM",
        "cars.pid.0104":              "Engine Load (calculated)",
        "cars.pid.0143":              "Engine Load (absolute)",
        "cars.pid.010E":              "Ignition Timing",
        "cars.pid.011F":              "Engine Run Time",
        "cars.pid.0142":              "Board Voltage",
        "cars.pid.ATRV":              "Adapter Voltage",
        "cars.pid.010D":              "Speed",
        "cars.pid.0131":              "Distance since DTC Clear",
        "cars.pid.0121":              "Distance with MIL on",
        "cars.pid.0130":              "Warm-ups since DTC Clear",
        "cars.pid.0105":              "Coolant",
        "cars.pid.010F":              "Intake Air",
        "cars.pid.0146":              "Ambient Air",
        "cars.pid.013C":              "Catalyst (Bank 1, Sensor 1)",
        "cars.pid.0111":              "Throttle Position",
        "cars.pid.0145":              "Relative Throttle",
        "cars.pid.0147":              "Throttle Sensor B",
        "cars.pid.0149":              "Accelerator Sensor D",
        "cars.pid.014A":              "Accelerator Sensor E",
        "cars.pid.014C":              "Throttle Actuator",
        "cars.pid.0103":              "Fuel System Status",
        "cars.pid.0106":              "Short-term Trim (Bank 1)",
        "cars.pid.0107":              "Long-term Trim (Bank 1)",
        "cars.pid.0156":              "Long-term Trim Sec. (Bank 1)",
        "cars.pid.0134":              "Lambda Bank 1, Sensor 1",
        "cars.pid.0144":              "Lambda Target",
        "cars.pid.0115":              "O2 Sensor Bank 1, Sensor 2",
        "cars.pid.0110":              "MAF (Air Mass)",
        "cars.pid.012F":              "Fuel Level",
        "cars.pid.0123":              "Fuel Rail Pressure",
        "cars.pid.012E":              "EVAP Purge",
        "cars.pid.0133":              "Barometric Pressure",
        "cars.pid.DTC":               "Stored Faults",
        "cars.pid.PENDING_DTC":       "Pending Faults",
        "cars.pid.0141":              "Monitor Status this Trip",
        "cars.trip.start":            "Start",
        "cars.trip.end":              "End",
        "cars.trip.duration":         "Duration",
        "cars.trip.distance":         "Distance",
        "cars.trip.max_speed":        "Top Speed",
        "cars.trip.avg_speed":        "Average Speed",
        "cars.trip.samples":          "Samples",
        "cars.trip.route":            "Route",
        "cars.trip.speed_chart":      "Speed (km/h)",
        "cars.trip.no_data":          "No data for this trip.",
        "cars.trip.ongoing":          "ongoing",
        "cars.trip.title":            "Trip #{id}",
        "cars.trip.delete_title":     "Delete trip?",
        "cars.trip.delete_body":      "This trip and all recorded data will be permanently deleted.",
        "cars.trip.delete_confirm":   "Delete",
        "cars.trip.delete_cancel":    "Cancel",
        "cars.trip.delete_multi_body": "{n} trips and all their recorded data will be permanently deleted.",
        "cars.trip.selected_count":    "{n} selected",
        "cars.vehicle.delete_title":   "Delete vehicle?",
        "cars.vehicle.delete_body":    "This vehicle, all trips and all scans will be permanently deleted.",
        "cars.category.scans":            "Scan History",
        "cars.scans.empty":               "No scans recorded for this vehicle yet.",
        "cars.category.acceleration_runs": "Acceleration Runs",
        "cars.accel_runs.empty":          "No acceleration runs recorded for this vehicle yet.",
        "cars.accel_run.title":           "Run {date}",
        "cars.accel_run.delete_title":    "Delete Run?",
        "cars.accel_run.delete_body":     "The acceleration run will be permanently deleted.",
        "cars.accel_run.max_obd":         "OBD Top Speed",
        "cars.accel_run.max_gps":         "GPS Top Speed",
        "cars.accel_run.max_g":           "Peak G-Force",
        "cars.accel_run.replay":          "Replay",
        "cars.scan.title":            "Scan {date}",
        "cars.scan.delete_title":     "Delete Scan?",
        "cars.scan.delete_body":      "The scan log will be permanently deleted.",
        "cars.scan.date":             "Date",
        "cars.scan.protocol":         "Protocol",
        "cars.scan.dtc_count":        "Active DTCs",
        "cars.scan.pending_count":    "Pending DTCs",
        "cars.scan.pids_count":       "Supported PIDs",
        "cars.scan.dtcs":             "Fault codes",
        "cars.scan.dtcs_none":        "No fault codes",
        "cars.scan.pending_dtcs":     "Pending fault codes",
        "cars.scan.trend_up":         "↑ {delta} more than previous scan",
        "cars.scan.trend_down":       "↓ {delta} fewer than previous scan",
        "cars.scan.trend_same":       "Unchanged from previous scan",
        "cars.scan.trend_first":      "First scan",
        "window.title": "DrivePulse",
        "settings.tooltip": "Settings",
    },
    "de": {
        "acceleration.title": "Beschleunigung",
        "acceleration.ready": "Bereit. Start drücken und losfahren.",
        "acceleration.armed": "Scharf. Zeit startet bei erkannter Beschleunigung.",
        "acceleration.running": "Messung läuft...",
        "acceleration.done": "Messung abgeschlossen.",
        "acceleration.g": "G: {value}",
        "acceleration.g.empty": "G: --",
        "acceleration.vmax": "Vmax {value}",
        "acceleration.vmax.empty": "Vmax --",
        "acceleration.vmax.in": "in",
        "acceleration.gmax": "G·max {value}",
        "acceleration.gmax.empty": "G·max --",
        "acceleration.start": "Start",
        "acceleration.abort": "Abbruch",
        "acceleration.reset": "Reset",
        "acceleration.best": "Ø",
        "acceleration.obd": "OBD",
        "acceleration.gps": "GPS",
        "acceleration.gforce_trigger": "Messung starten wenn G-Kräfte wirken",
        "acceleration.replay": "Wiederholen",
        "acceleration.replay.running": "Wiedergabe...",
        "cars.metric.speed_kmh":   "Geschwindigkeit",
        "cars.metric.rpm":         "Drehzahl",
        "cars.metric.coolant_c":   "Kühlmitteltemp.",
        "cars.metric.intake_c":    "Ansauglufttemp.",
        "cars.metric.throttle_pct": "Drosselklappe",
        "cars.metric.engine_load": "Motorlast",
        "cars.metric.maf_gps":     "Luftmasse",
        "cars.metric.voltage_v":   "Spannung",
        "cars.metric.accel_g":     "Beschleunigung",
        "cars.metric.fuel_pct":    "Kraftstoff",
        "settings.title": "Einstellungen",
        "settings.display": "Anzeige",
        "settings.units": "Einheiten",
        "settings.speed": "Geschwindigkeit",
        "settings.metric": "Metrisch (km/h)",
        "settings.imperial": "Imperial (mph)",
        "settings.language": "Sprache",
        "settings.language.en": "English",
        "settings.language.de": "Deutsch",
        "settings.auto_rotate": "Automatisch drehen",
        "settings.auto_rotate.subtitle": "Anzeige an die Geräteneigung anpassen",
        "settings.mock_mode": "Mock-Modus",
        "settings.mock_mode.subtitle": "OBD- und GPS-Daten ohne Hardware simulieren",
        "settings.obd": "OBD",
        "settings.obd_dongle": "Dongle",
        "settings.obd_dongle.auto": "Automatisch erkennen",
        "settings.obd_dongle.none_found": "Kein Dongle erkannt",
        "settings.gauge_theme": "Tacho-Design",
        "settings.gauge_theme.cockpit": "Cockpit",
        "settings.gauge_theme.neon": "Neon",
        "settings.gauge_theme.minimal": "Minimal",
        "settings.gauge_theme.digital": "Digital",
        "settings.gauge_theme.racing": "Racing",
        "settings.gauge_theme.analog": "Analog",
        "gauge.rpm": "Drehzahl",
        "gauge.speed": "Geschwindigkeit",
        "gauge.coolant": "Kühlmittel",
        "gauge.source.obd": "OBD",
        "gauge.source.gps": "GPS",
        "dashboard.rpm": "Drehzahl",
        "dashboard.rpm.unit": "U/min",
        "dashboard.coolant": "Kühlmittel",
        "dashboard.heading": "Richtung",
        "dashboard.fuel": "Kraftstoff",
        "dashboard.cardinal.N":  "N",
        "dashboard.cardinal.NE": "NO",
        "dashboard.cardinal.E":  "O",
        "dashboard.cardinal.SE": "SO",
        "dashboard.cardinal.S":  "S",
        "dashboard.cardinal.SW": "SW",
        "dashboard.cardinal.W":  "W",
        "dashboard.cardinal.NW": "NW",
        "status.connecting": "Verbinde...",
        "status.obd": "OBD",
        "status.gps": "GPS",

        "status.updated": "{status} | letzte Aktualisierung: {time}",
        "nav.gauges": "Tachos",
        "nav.acceleration": "Beschleunigung",
        "nav.cars": "Autos",
        "cars.list.intro": "Wähle ein Fahrzeug, um seine Werte anzuzeigen.",
        "cars.empty": "Noch keine Fahrzeuge gespeichert. Verbinde dich mit einem OBD-Dongle — beim ersten Scan wird automatisch ein Profil angelegt.",
        "cars.live.title": "Live-Verbindung",
        "cars.live.subtitle": "Keine OBD-Verbindung",
        "cars.live.connected": "OBD verbunden",
        "cars.unknown": "Fahrzeug",
        "cars.back": "Zurück",
        "cars.categories": "Kategorien",
        "cars.source.label": "Quelle: {source}",
        "cars.dtc.none": "Keine Fehler",
        "cars.trips.empty": "Für dieses Fahrzeug sind noch keine Fahrten aufgezeichnet.",
        "cars.category.vehicle":      "Fahrzeug",
        "cars.category.engine":       "Motor",
        "cars.category.drive":        "Geschwindigkeit & Strecke",
        "cars.category.temperatures": "Temperaturen",
        "cars.category.throttle":     "Gas & Drosselklappe",
        "cars.category.mixture":      "Gemisch & Lambda",
        "cars.category.fuel":         "Kraftstoff & Luft",
        "cars.category.diagnostics":  "Diagnose",
        "cars.category.trips":        "Fahrten",
        "cars.pid.VIN":               "Fahrgestellnummer (VIN)",
        "cars.pid.CAL":               "Steuergerät-Software (Cal-ID)",
        "cars.pid.CVN":               "Software-Prüfnummer (CVN)",
        "cars.pid.PROTO":             "Diagnose-Protokoll",
        "cars.pid.011C":              "OBD-Norm",
        "cars.pid.SCAN_DATE":         "Letzter Scan",
        "cars.pid.010C":              "Drehzahl",
        "cars.pid.0104":              "Motorlast (berechnet)",
        "cars.pid.0143":              "Motorlast (absolut)",
        "cars.pid.010E":              "Zündzeitpunkt",
        "cars.pid.011F":              "Motorlaufzeit seit Start",
        "cars.pid.0142":              "Bordnetzspannung",
        "cars.pid.ATRV":              "Adapter-Spannung",
        "cars.pid.010D":              "Geschwindigkeit",
        "cars.pid.0131":              "Strecke seit Fehlerlöschung",
        "cars.pid.0121":              "Strecke mit Motorkontrollleuchte",
        "cars.pid.0130":              "Warmlaufzyklen seit Fehlerlöschung",
        "cars.pid.0105":              "Kühlmittel",
        "cars.pid.010F":              "Ansaugluft",
        "cars.pid.0146":              "Außenluft",
        "cars.pid.013C":              "Katalysator (Bank 1, Sensor 1)",
        "cars.pid.0111":              "Drosselklappe",
        "cars.pid.0145":              "Drosselklappe (relativ)",
        "cars.pid.0147":              "Drosselklappe Sensor B",
        "cars.pid.0149":              "Gaspedal Sensor D",
        "cars.pid.014A":              "Gaspedal Sensor E",
        "cars.pid.014C":              "Drosselklappen-Sollwert",
        "cars.pid.0103":              "Kraftstoffsystem-Status",
        "cars.pid.0106":              "Kurzzeit-Korrektur (Bank 1)",
        "cars.pid.0107":              "Langzeit-Korrektur (Bank 1)",
        "cars.pid.0156":              "Langzeit-Korrektur Sekundärsonde (Bank 1)",
        "cars.pid.0134":              "Lambda Bank 1, Sensor 1",
        "cars.pid.0144":              "Lambda-Sollwert",
        "cars.pid.0115":              "Lambdasonde Bank 1, Sensor 2",
        "cars.pid.0110":              "Luftmasse (MAF)",
        "cars.pid.012F":              "Tankfüllstand",
        "cars.pid.0123":              "Kraftstoff-Raildruck",
        "cars.pid.012E":              "Tankentlüftung",
        "cars.pid.0133":              "Luftdruck",
        "cars.pid.DTC":               "Gespeicherte Fehler",
        "cars.pid.PENDING_DTC":       "Ausstehende Fehler",
        "cars.pid.0141":              "Monitor-Status diese Fahrt",
        "cars.trip.start":            "Start",
        "cars.trip.end":              "Ende",
        "cars.trip.duration":         "Dauer",
        "cars.trip.distance":         "Strecke",
        "cars.trip.max_speed":        "Höchstgeschwindigkeit",
        "cars.trip.avg_speed":        "Durchschnitt",
        "cars.trip.samples":          "Samples",
        "cars.trip.route":            "Strecke",
        "cars.trip.speed_chart":      "Geschwindigkeit (km/h)",
        "cars.trip.no_data":          "Keine Messwerte für diese Fahrt.",
        "cars.trip.ongoing":          "laufend",
        "cars.trip.title":            "Fahrt #{id}",
        "cars.trip.delete_title":     "Fahrt löschen?",
        "cars.trip.delete_body":      "Diese Fahrt und alle aufgezeichneten Daten werden dauerhaft gelöscht.",
        "cars.trip.delete_confirm":   "Löschen",
        "cars.trip.delete_cancel":    "Abbrechen",
        "cars.trip.delete_multi_body": "{n} Fahrten und alle aufgezeichneten Daten werden dauerhaft gelöscht.",
        "cars.trip.selected_count":    "{n} ausgewählt",
        "cars.vehicle.delete_title":   "Fahrzeug löschen?",
        "cars.vehicle.delete_body":    "Dieses Fahrzeug mit allen Fahrten und Scans wird dauerhaft gelöscht.",
        "cars.category.scans":            "Scan-Verlauf",
        "cars.scans.empty":               "Noch keine Scans für dieses Fahrzeug gespeichert.",
        "cars.category.acceleration_runs": "Beschleunigungsläufe",
        "cars.accel_runs.empty":          "Noch keine Beschleunigungsläufe für dieses Fahrzeug gespeichert.",
        "cars.accel_run.title":           "Lauf {date}",
        "cars.accel_run.delete_title":    "Lauf löschen?",
        "cars.accel_run.delete_body":     "Der Beschleunigungslauf wird dauerhaft gelöscht.",
        "cars.accel_run.max_obd":         "OBD-Topgeschwindigkeit",
        "cars.accel_run.max_gps":         "GPS-Topgeschwindigkeit",
        "cars.accel_run.max_g":           "Maximale G-Kraft",
        "cars.accel_run.replay":          "Wiederholen",
        "cars.scan.title":            "Scan {date}",
        "cars.scan.delete_title":     "Scan löschen?",
        "cars.scan.delete_body":      "Das Scan-Protokoll wird dauerhaft gelöscht.",
        "cars.scan.date":             "Datum",
        "cars.scan.protocol":         "Protokoll",
        "cars.scan.dtc_count":        "Aktive Fehler",
        "cars.scan.pending_count":    "Ausstehende Fehler",
        "cars.scan.pids_count":       "Unterstützte PIDs",
        "cars.scan.dtcs":             "Fehlercodes",
        "cars.scan.dtcs_none":        "Keine Fehlercodes",
        "cars.scan.pending_dtcs":     "Ausstehende Fehlercodes",
        "cars.scan.trend_up":         "↑ {delta} mehr als beim letzten Scan",
        "cars.scan.trend_down":       "↓ {delta} weniger als beim letzten Scan",
        "cars.scan.trend_same":       "Unverändert zum letzten Scan",
        "cars.scan.trend_first":      "Erster Scan",
        "window.title": "DrivePulse",
        "settings.tooltip": "Einstellungen",
    },
}

# ---------------------------------------------------------------------------
# Language helpers
# ---------------------------------------------------------------------------


def _normalize_language(language: str | None) -> str:
    if not language:
        return SOURCE_LANGUAGE
    normalized = language.split(".", 1)[0].split("_", 1)[0].split("-", 1)[0].lower()
    return normalized if normalized in SUPPORTED_LANGUAGES else SOURCE_LANGUAGE


def _detect_language() -> str:
    return _normalize_language(os.environ.get("DRIVEPULSE_LANG") or os.environ.get("LANG"))


def _translate(language: str, key: str, **values: object) -> str:
    text = TRANSLATIONS.get(_normalize_language(language), {}).get(key)
    if text is None:
        text = TRANSLATIONS[SOURCE_LANGUAGE].get(key, key)
    return text.format(**values) if values else text


# ---------------------------------------------------------------------------
# GTK helpers
# ---------------------------------------------------------------------------


def _make_label_responsive(label: Gtk.Label, max_width_chars: int = 34, xalign: float = 0.0) -> Gtk.Label:
    label.set_wrap(True)
    label.set_wrap_mode(Pango.WrapMode.WORD_CHAR)
    label.set_max_width_chars(max_width_chars)
    label.set_xalign(xalign)
    label.set_hexpand(True)
    return label
